import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import Logo from "@/Components/Logo/Logo";


const inter = Kanit({
  subsets: ["latin"],
 weight:["100","200","300","400","500","600","700","800","900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Logo/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
